# Generated by Django 4.2.16 on 2024-11-11 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("last_name", models.CharField(max_length=150, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=150, verbose_name="Имя")),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Отчество"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        default="default_avatar.png",
                        upload_to="users_avatars/",
                        verbose_name="Аватар",
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Включен")),
                (
                    "notify_tasks",
                    models.BooleanField(
                        default=True, verbose_name="Оповещать о задачах"
                    ),
                ),
                (
                    "notify_messages",
                    models.BooleanField(
                        default=True, verbose_name="Оповещать о сообщениях"
                    ),
                ),
                (
                    "notify_documents",
                    models.BooleanField(
                        default=True, verbose_name="Оповещать о документах"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Включен")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль пользователя",
                "verbose_name_plural": "Профили пользователей",
            },
        ),
    ]
