# Generated by Django 5.1.3 on 2024-11-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='erpuser',
            name='first_name',
            field=models.CharField(default='Имя', max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='erpuser',
            name='last_name',
            field=models.CharField(default='Фамилия', max_length=150, verbose_name='Фамилия'),
        ),
    ]
