# Generated by Django 5.1.3 on 2024-11-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_erpuser_middle_name_alter_erpuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpuser',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='Статус персонала'),
        ),
    ]
