# Generated by Django 5.1.3 on 2024-11-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_erpuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpuser',
            name='avatar',
            field=models.ImageField(blank=True, default='media/users/blank_avatar.jpg', null=True, upload_to='media/users/avatar', verbose_name='Аватар'),
        ),
    ]
