# Generated by Django 5.1.3 on 2024-11-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_erpuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpuser',
            name='avatar',
            field=models.ImageField(blank=True, default='users/blank_avatar.jpg', null=True, upload_to='users/avatar', verbose_name='Аватар'),
        ),
    ]
