# Generated by Django 5.1.3 on 2024-11-23 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_erpuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=150, verbose_name='Краткое наименование')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Адрес юридический')),
                ('mail_address', models.CharField(blank=True, max_length=250, verbose_name='Адрес почтовый')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.branch', verbose_name='Филиал')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники организации',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_manager_set', to='core.employee', verbose_name='Заведующий'),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=150, verbose_name='Краткое наименование')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Адрес юридический')),
                ('mail_address', models.CharField(blank=True, max_length=250, verbose_name='Адрес почтовый')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('site', models.URLField(blank=True, verbose_name='Сайт')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_manager_set', to='core.employee', verbose_name='Директор')),
            ],
            options={
                'verbose_name': 'Данные организации',
                'verbose_name_plural': 'Список организаций',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='Организация'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование должности')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.position', verbose_name='Руководитель')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Список должностей',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.position', verbose_name='Должность'),
        ),
    ]
