# Generated by Django 5.1.3 on 2024-11-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_employee_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.CharField(choices=[('FIRE', 'Срочно'), ('SIMPLE', 'Стандартно'), ('VIEW', 'К рассмотрению')], default='SIMPLE', max_length=150, verbose_name='Важность')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Сообщение аппбара',
                'verbose_name_plural': 'Сообщения для шапки',
            },
        ),
    ]
