# Generated by Django 5.1.3 on 2024-11-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_warnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warnings',
            name='importance',
            field=models.CharField(choices=[('Срочно', 'Срочно'), ('Срочно', 'Срочно'), ('Рассмотреть', 'Рассмотреть')], default='Срочно', max_length=150, verbose_name='Важность'),
        ),
    ]
