# Generated by Django 5.1.3 on 2024-11-23 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_warnings_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='warnings',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Включено'),
        ),
        migrations.AddField(
            model_name='warnings',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='warnings',
            name='days',
            field=models.IntegerField(null=True, verbose_name='Количество дней публикации'),
        ),
    ]
