# Generated by Django 5.1.3 on 2024-11-23 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_warnings_active_warnings_date_warnings_days'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Warnings',
            new_name='Notification',
        ),
    ]
