# Generated by Django 5.1.3 on 2024-11-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_notification_link_alter_notification_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dismissed',
            field=models.BooleanField(default=False, verbose_name='Уволен'),
        ),
        migrations.AddField(
            model_name='employee',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата увольнения'),
        ),
        migrations.AddField(
            model_name='employee',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приема'),
        ),
        migrations.AddField(
            model_name='employee',
            name='vacancy',
            field=models.BooleanField(default=False, verbose_name='Отпуск'),
        ),
    ]
