# Generated by Django 5.1.3 on 2024-11-24 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_employee_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, max_length=250, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.branch', verbose_name='Филиал'),
        ),
    ]
